version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Clean Temp
          command: ./gradlew clean
      - run:
          name: Build Libs
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Publish Maven
          command: ./gradlew publishMaven