name: VioletTest
version: ${version}
author: Himmelt
main: org.soraworld.violettest.VioletTest
website: https://github.com/Himmelt/Violet
description: Violet Spigot Test Plugin.
depend:
  - Violet
permissions:
  violettest.admin:
    default: op
