name: Violet
version: 2.2.8
author: Himmelt
main: org.soraworld.violet.SpigotViolet
website: https://github.com/Himmelt/Violet
description: Violet Library Plugin.
permissions:
  violet.admin:
    default: op
